# Project-wide Gradle settings
# https://developer.android.com/build/gradle-migrate

# AndroidX package structure to make it clearer which packages are being used
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable native build with CMake
android.enableCmake=true

# Disable the new build caching feature
org.gradle.caching=true
